"""
PDF Report Generator for Breast Cancer Detection Results
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os

class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
    
    def setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#0369a1'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#0891b2'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12,
            alignment=TA_LEFT
        ))
    
    def generate_report(self, prediction_data, output_path='reports/prediction_report.pdf', report_type='patient'):
        """
        Generate PDF report for prediction
        
        Args:
            prediction_data: Dictionary containing prediction results
            output_path: Path where PDF will be saved
            report_type: 'patient', 'technical', or 'symptom'
        """
        
        # Create reports directory
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Generate appropriate report type
        if report_type == 'symptom':
            return self._generate_symptom_report(prediction_data, output_path)
        elif report_type == 'technical':
            return self._generate_technical_report(prediction_data, output_path)
        else:
            return self._generate_patient_report(prediction_data, output_path)
    
    def _generate_patient_report(self, prediction_data, output_path):
        """Generate patient-friendly report with simple, clear information"""
        
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        
        # Title
        title = Paragraph("Your Breast Cancer Screening Results", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.3*inch))
        
        # Report metadata
        report_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        metadata = Paragraph(f"<b>Report Date:</b> {report_date}", self.styles['CustomBody'])
        story.append(metadata)
        story.append(Spacer(1, 0.2*inch))
        
        # Disclaimer
        disclaimer = Paragraph(
            "<b>IMPORTANT:</b> This report is generated by an AI screening system to assist healthcare "
            "professionals. It is NOT a final diagnosis. Please discuss these results with your doctor "
            "who will provide proper medical advice and next steps.",
            ParagraphStyle(
                'Disclaimer',
                parent=self.styles['Normal'],
                fontSize=10,
                textColor=colors.HexColor('#991b1b'),
                borderColor=colors.HexColor('#fca5a5'),
                borderWidth=2,
                borderPadding=12,
                spaceAfter=20,
                backColor=colors.HexColor('#fef2f2')
            )
        )
        story.append(disclaimer)
        story.append(Spacer(1, 0.3*inch))
        
        # Screening Result Section
        story.append(Paragraph("Your Screening Result", self.styles['CustomHeading']))
        
        prediction_label = prediction_data['best_model']['prediction_label']
        confidence = prediction_data['best_model']['confidence'] * 100
        
        # Result box with clear messaging
        if prediction_label == 'Malignant':
            result_color = colors.HexColor('#dc2626')
            result_bg = colors.HexColor('#fee2e2')
            result_message = "Abnormal Result Detected"
            result_explanation = (
                "The screening has detected patterns that may indicate abnormal cells. "
                "This does NOT mean you have cancer. Further medical tests are needed to confirm."
            )
        else:
            result_color = colors.HexColor('#16a34a')
            result_bg = colors.HexColor('#dcfce7')
            result_message = "Normal Result"
            result_explanation = (
                "The screening shows normal patterns. However, continue regular check-ups "
                "and report any changes to your doctor."
            )
        
        result_data = [
            ['Result', result_message],
            ['Confidence', f"{confidence:.0f}%"],
            ['What This Means', result_explanation]
        ]
        
        result_table = Table(result_data, colWidths=[1.8*inch, 4.2*inch])
        result_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e0f2fe')),
            ('BACKGROUND', (1, 0), (1, 0), result_bg),
            ('TEXTCOLOR', (1, 0), (1, 0), result_color),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('FONTSIZE', (1, 0), (1, 0), 14),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 1.5, colors.grey),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ]))
        
        story.append(result_table)
        story.append(Spacer(1, 0.4*inch))
        
        # Next Steps Section
        story.append(Paragraph("What Should You Do Next?", self.styles['CustomHeading']))
        
        if prediction_label == 'Malignant':
            next_steps = [
                ("1. Schedule an Appointment", 
                 "Contact your doctor immediately to discuss these results."),
                ("2. Additional Tests", 
                 "Your doctor may recommend a biopsy or imaging tests for confirmation."),
                ("3. Don't Panic", 
                 "Many abnormal screenings turn out to be benign after further testing."),
                ("4. Bring This Report", 
                 "Show this report to your healthcare provider during your visit."),
                ("5. Ask Questions", 
                 "Write down any questions you have for your doctor.")
            ]
        else:
            next_steps = [
                ("1. Continue Regular Screenings", 
                 "Follow your doctor's recommended screening schedule."),
                ("2. Maintain Healthy Habits", 
                 "Exercise regularly, eat a balanced diet, and avoid smoking."),
                ("3. Know Your Body", 
                 "Perform monthly self-examinations and report any changes."),
                ("4. Stay Informed", 
                 "Learn about breast health and risk factors."),
                ("5. Schedule Follow-Up", 
                 "Book your next screening appointment as recommended.")
            ]
        
        for step_title, step_desc in next_steps:
            story.append(Paragraph(f"<b>{step_title}</b>", self.styles['CustomBody']))
            story.append(Paragraph(step_desc, 
                ParagraphStyle('StepDesc', parent=self.styles['Normal'], 
                              fontSize=10, leftIndent=20, spaceAfter=10)))
        
        story.append(Spacer(1, 0.3*inch))
        
        # Understanding Your Results Section
        story.append(Paragraph("Understanding Your Results", self.styles['CustomHeading']))
        
        understanding = [
            ("<b>Confidence Level:</b>", 
             f"The system is {confidence:.0f}% confident in this result. Higher confidence means "
             "the patterns are clearer, but only a doctor can make a final diagnosis."),
            ("<b>This is a Screening Tool:</b>", 
             "This AI system helps identify patterns that need medical attention. It cannot "
             "replace a doctor's examination and professional judgment."),
            ("<b>Next Steps Are Important:</b>", 
             "Whether your result is normal or abnormal, following up with your healthcare "
             "provider is essential for your health.")
        ]
        
        for title, desc in understanding:
            story.append(Paragraph(f"{title} {desc}", 
                ParagraphStyle('Understanding', parent=self.styles['Normal'], 
                              fontSize=10, spaceAfter=12, leading=14)))
        
        story.append(Spacer(1, 0.3*inch))
        
        # Contact Information Box
        contact_box = Paragraph(
            "<b>Need Help?</b><br/>"
            "If you have questions about this report, please contact your healthcare provider "
            "or call our support line. Do not delay seeking medical advice.",
            ParagraphStyle(
                'ContactBox',
                parent=self.styles['Normal'],
                fontSize=10,
                borderColor=colors.HexColor('#0891b2'),
                borderWidth=2,
                borderPadding=12,
                backColor=colors.HexColor('#ecfeff'),
                spaceAfter=20
            )
        )
        story.append(contact_box)
        
        # Footer
        footer_text = Paragraph(
            f"<i>Report ID: {prediction_data.get('report_id', 'N/A')} | "
            f"Generated by AI Breast Cancer Screening System | For Medical Use Only</i>",
            ParagraphStyle(
                'Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey,
                alignment=TA_CENTER
            )
        )
        story.append(Spacer(1, 0.5*inch))
        story.append(footer_text)
        
        # Build PDF
        doc.build(story)
        return output_path
    
    def _generate_technical_report(self, prediction_data, output_path):
        """Generate technical report with model details for doctors/researchers"""
        
        # Create reports directory
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Create PDF document
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        
        # Title
        title = Paragraph("Breast Cancer Detection Report", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.3*inch))
        
        # Report metadata
        report_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        metadata = Paragraph(f"<b>Report Generated:</b> {report_date}", self.styles['CustomBody'])
        story.append(metadata)
        story.append(Spacer(1, 0.2*inch))
        
        # Disclaimer
        disclaimer = Paragraph(
            "<b>MEDICAL DISCLAIMER:</b> This report is generated by an AI system for educational "
            "and research purposes only. It should NOT be used as a substitute for professional "
            "medical advice, diagnosis, or treatment. Always consult qualified healthcare professionals.",
            ParagraphStyle(
                'Disclaimer',
                parent=self.styles['Normal'],
                fontSize=9,
                textColor=colors.red,
                borderColor=colors.red,
                borderWidth=1,
                borderPadding=10,
                spaceAfter=20
            )
        )
        story.append(disclaimer)
        story.append(Spacer(1, 0.3*inch))
        
        # Prediction Results Section
        story.append(Paragraph("Prediction Results", self.styles['CustomHeading']))
        
        # Main prediction result
        prediction_label = prediction_data['best_model']['prediction_label']
        confidence = prediction_data['best_model']['confidence'] * 100
        
        result_color = colors.red if prediction_label == 'Malignant' else colors.green
        
        result_data = [
            ['Diagnosis', prediction_label],
            ['Confidence Level', f"{confidence:.2f}%"],
            ['Best Model', prediction_data['best_model']['name']],
            ['Risk Assessment', prediction_data.get('risk_assessment', {}).get('message', 'N/A')]
        ]
        
        result_table = Table(result_data, colWidths=[2*inch, 4*inch])
        result_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e0f2fe')),
            ('BACKGROUND', (1, 0), (1, 0), result_color),
            ('TEXTCOLOR', (1, 0), (1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('FONTSIZE', (1, 0), (1, 0), 14),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        
        story.append(result_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Model Comparison Section
        if 'all_models' in prediction_data and prediction_data['all_models'] and len(prediction_data['all_models']) > 1:
            story.append(Paragraph("Model Comparison", self.styles['CustomHeading']))
            
            model_data = [['Model Name', 'Prediction', 'Confidence']]
            for model_name, model_result in prediction_data['all_models'].items():
                model_data.append([
                    model_name,
                    model_result.get('prediction_label', 'N/A'),
                    f"{model_result.get('confidence', 0)*100:.2f}%"
                ])
            
            model_table = Table(model_data, colWidths=[2.5*inch, 2*inch, 1.5*inch])
            model_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0891b2')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ]))
            
            story.append(model_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Feature Importance Section
        if 'feature_importance' in prediction_data and prediction_data['feature_importance'] and len(prediction_data['feature_importance']) > 0:
            story.append(Paragraph("Top Contributing Features", self.styles['CustomHeading']))
            
            feature_data = [['Feature Name', 'Value', 'Importance']]
            for feature in prediction_data['feature_importance'][:10]:
                feature_data.append([
                    feature.get('name', 'N/A'),
                    f"{feature.get('value', 0):.4f}",
                    f"{feature.get('importance', 0):.4f}"
                ])
            
            feature_table = Table(feature_data, colWidths=[3*inch, 1.5*inch, 1.5*inch])
            feature_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0891b2')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            
            story.append(feature_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Recommendations Section
        story.append(Paragraph("Recommendations", self.styles['CustomHeading']))
        
        if prediction_label == 'Malignant':
            recommendations = [
                "• Immediate consultation with an oncologist is strongly recommended",
                "• Additional diagnostic tests (biopsy, imaging) should be performed",
                "• Discuss treatment options with healthcare team",
                "• Consider seeking a second opinion from a specialist",
                "• Maintain detailed medical records and test results"
            ]
        else:
            recommendations = [
                "• Continue regular screening and monitoring",
                "• Maintain healthy lifestyle and preventive measures",
                "• Schedule follow-up appointments as recommended",
                "• Report any changes or symptoms to healthcare provider",
                "• Stay informed about breast health"
            ]
        
        for rec in recommendations:
            story.append(Paragraph(rec, self.styles['CustomBody']))
        
        story.append(Spacer(1, 0.3*inch))
        
        # Footer
        footer_text = Paragraph(
            "<i>This report was generated by an AI-based Breast Cancer Detection System. "
            "Report ID: " + prediction_data.get('report_id', 'N/A') + "</i>",
            ParagraphStyle(
                'Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey,
                alignment=TA_CENTER
            )
        )
        story.append(Spacer(1, 0.5*inch))
        story.append(footer_text)
        
        # Build PDF
        doc.build(story)
        
        return output_path
    
    def _generate_technical_report(self, prediction_data, output_path):
        """Generate technical report with model details for doctors/researchers"""
        
        # This is the original detailed report
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []

        
        # Title
        title = Paragraph("Breast Cancer Detection Report (Technical)", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.3*inch))
        
        # Report metadata
        report_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        metadata = Paragraph(f"<b>Report Generated:</b> {report_date}", self.styles['CustomBody'])
        story.append(metadata)
        story.append(Spacer(1, 0.2*inch))
        
        # Disclaimer
        disclaimer = Paragraph(
            "<b>MEDICAL DISCLAIMER:</b> This report is generated by an AI system for educational "
            "and research purposes only. It should NOT be used as a substitute for professional "
            "medical advice, diagnosis, or treatment. Always consult qualified healthcare professionals.",
            ParagraphStyle(
                'Disclaimer',
                parent=self.styles['Normal'],
                fontSize=9,
                textColor=colors.red,
                borderColor=colors.red,
                borderWidth=1,
                borderPadding=10,
                spaceAfter=20
            )
        )
        story.append(disclaimer)
        story.append(Spacer(1, 0.3*inch))
        
        # Prediction Results Section
        story.append(Paragraph("Prediction Results", self.styles['CustomHeading']))
        
        # Main prediction result
        prediction_label = prediction_data['best_model']['prediction_label']
        confidence = prediction_data['best_model']['confidence'] * 100
        
        result_color = colors.red if prediction_label == 'Malignant' else colors.green
        
        result_data = [
            ['Diagnosis', prediction_label],
            ['Confidence Level', f"{confidence:.2f}%"],
            ['Best Model', prediction_data['best_model']['name']],
            ['Risk Assessment', prediction_data.get('risk_assessment', {}).get('message', 'N/A')]
        ]
        
        result_table = Table(result_data, colWidths=[2*inch, 4*inch])
        result_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e0f2fe')),
            ('BACKGROUND', (1, 0), (1, 0), result_color),
            ('TEXTCOLOR', (1, 0), (1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('FONTSIZE', (1, 0), (1, 0), 14),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        
        story.append(result_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Model Comparison Section
        if 'all_models' in prediction_data and prediction_data['all_models'] and len(prediction_data['all_models']) > 1:
            story.append(Paragraph("Model Comparison", self.styles['CustomHeading']))
            
            model_data = [['Model Name', 'Prediction', 'Confidence']]
            for model_name, model_result in prediction_data['all_models'].items():
                model_data.append([
                    model_name,
                    model_result.get('prediction_label', 'N/A'),
                    f"{model_result.get('confidence', 0)*100:.2f}%"
                ])
            
            model_table = Table(model_data, colWidths=[2.5*inch, 2*inch, 1.5*inch])
            model_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0891b2')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ]))
            
            story.append(model_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Feature Importance Section
        if 'feature_importance' in prediction_data and prediction_data['feature_importance'] and len(prediction_data['feature_importance']) > 0:
            story.append(Paragraph("Top Contributing Features", self.styles['CustomHeading']))
            
            feature_data = [['Feature Name', 'Value', 'Importance']]
            for feature in prediction_data['feature_importance'][:10]:
                feature_data.append([
                    feature.get('name', 'N/A'),
                    f"{feature.get('value', 0):.4f}",
                    f"{feature.get('importance', 0):.4f}"
                ])
            
            feature_table = Table(feature_data, colWidths=[3*inch, 1.5*inch, 1.5*inch])
            feature_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0891b2')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            
            story.append(feature_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Clinical Recommendations Section
        story.append(Paragraph("Clinical Recommendations", self.styles['CustomHeading']))
        
        if prediction_label == 'Malignant':
            recommendations = [
                "• Immediate consultation with an oncologist is strongly recommended",
                "• Additional diagnostic tests (biopsy, imaging) should be performed",
                "• Discuss treatment options with healthcare team",
                "• Consider seeking a second opinion from a specialist",
                "• Maintain detailed medical records and test results"
            ]
        else:
            recommendations = [
                "• Continue regular screening and monitoring",
                "• Maintain healthy lifestyle and preventive measures",
                "• Schedule follow-up appointments as recommended",
                "• Report any changes or symptoms to healthcare provider",
                "• Stay informed about breast health"
            ]
        
        for rec in recommendations:
            story.append(Paragraph(rec, self.styles['CustomBody']))
        
        story.append(Spacer(1, 0.3*inch))
        
        # Footer
        footer_text = Paragraph(
            "<i>This technical report was generated by an AI-based Breast Cancer Detection System. "
            "Report ID: " + prediction_data.get('report_id', 'N/A') + "</i>",
            ParagraphStyle(
                'Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey,
                alignment=TA_CENTER
            )
        )
        story.append(Spacer(1, 0.5*inch))
        story.append(footer_text)
        
        # Build PDF
        doc.build(story)
        return output_path

    def _generate_symptom_report(self, prediction_data, output_path):
        """Generate symptom-based analysis report"""
        
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        
        # Title
        title = Paragraph("Symptom-Based Breast Cancer Screening Report", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.3*inch))
        
        # Report metadata
        report_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        metadata = Paragraph(f"<b>Report Date:</b> {report_date}<br/><b>Report ID:</b> {prediction_data.get('report_id', 'N/A')}", self.styles['CustomBody'])
        story.append(metadata)
        story.append(Spacer(1, 0.2*inch))
        
        # Disclaimer
        disclaimer = Paragraph(
            "<b>IMPORTANT MEDICAL DISCLAIMER:</b> This report is based on self-reported symptoms and AI analysis. "
            "It is NOT a medical diagnosis. This screening tool is designed to help identify potential concerns "
            "that require professional medical evaluation. Always consult with a qualified healthcare provider "
            "for proper diagnosis and treatment.",
            ParagraphStyle(
                'Disclaimer',
                parent=self.styles['Normal'],
                fontSize=10,
                textColor=colors.HexColor('#991b1b'),
                borderColor=colors.HexColor('#fca5a5'),
                borderWidth=2,
                borderPadding=12,
                spaceAfter=20,
                backColor=colors.HexColor('#fef2f2')
            )
        )
        story.append(disclaimer)
        story.append(Spacer(1, 0.3*inch))
        
        # Screening Result Section
        story.append(Paragraph("Screening Result", self.styles['CustomHeading']))
        
        prediction_label = prediction_data['best_model']['prediction_label']
        confidence = prediction_data['best_model']['confidence'] * 100
        risk_assessment = prediction_data.get('risk_assessment', {})
        
        # Result box
        if prediction_label == 'Malignant':
            result_color = colors.HexColor('#dc2626')
            result_bg = colors.HexColor('#fee2e2')
            result_message = "Concerning Symptoms Detected"
        else:
            result_color = colors.HexColor('#16a34a')
            result_bg = colors.HexColor('#dcfce7')
            result_message = "Low Risk Symptoms"
        
        result_data = [
            ['Screening Result', result_message],
            ['AI Confidence', f"{confidence:.1f}%"],
            ['Risk Level', risk_assessment.get('risk_level', 'N/A')],
            ['Risk Score', f"{risk_assessment.get('risk_score', 0)} points"]
        ]
        
        result_table = Table(result_data, colWidths=[2*inch, 4*inch])
        result_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e0f2fe')),
            ('BACKGROUND', (1, 0), (1, 0), result_bg),
            ('TEXTCOLOR', (1, 0), (1, 0), result_color),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('FONTSIZE', (1, 0), (1, 0), 14),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 1.5, colors.grey),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        
        story.append(result_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Reported Symptoms Section
        symptoms_data = prediction_data.get('symptoms_data', {})
        if symptoms_data:
            story.append(Paragraph("Reported Symptoms Summary", self.styles['CustomHeading']))
            
            # Patient Information
            story.append(Paragraph("<b>Patient Information:</b>", self.styles['CustomBody']))
            patient_info = [
                ['Age', f"{symptoms_data.get('age', 'N/A')} years"],
                ['Family History', 'Yes' if symptoms_data.get('family_history') == 'yes' else 'No'],
                ['Menstrual Status', symptoms_data.get('menstrual_status', 'N/A').replace('_', ' ').title()],
                ['Previous Conditions', symptoms_data.get('previous_conditions', 'none').replace('_', ' ').title()]
            ]
            
            patient_table = Table(patient_info, colWidths=[2*inch, 4*inch])
            patient_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f9ff')),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            
            story.append(patient_table)
            story.append(Spacer(1, 0.2*inch))
            
            # Physical Symptoms
            story.append(Paragraph("<b>Physical Examination Findings:</b>", self.styles['CustomBody']))
            physical_symptoms = [
                ['Breast Lump', symptoms_data.get('lump', 'none').title()],
                ['Lump Mobility', symptoms_data.get('lump_mobility', 'N/A').replace('_', ' ').title()],
                ['Armpit Lump', symptoms_data.get('armpit_lump', 'none').title()],
                ['Pain Level', symptoms_data.get('pain', 'none').title()],
                ['Skin Changes', symptoms_data.get('skin_change', 'none').title()],
                ['Skin Texture', symptoms_data.get('skin_texture', 'normal').replace('_', ' ').title()],
                ['Nipple Discharge', symptoms_data.get('nipple_discharge', 'none').title()],
                ['Nipple Retraction', symptoms_data.get('nipple_retraction', 'none').title()],
                ['Breast Shape Change', symptoms_data.get('breast_shape_change', 'none').replace('_', ' ').title()],
                ['Symptom Duration', symptoms_data.get('symptom_duration', 'N/A').title()]
            ]
            
            physical_table = Table(physical_symptoms, colWidths=[2*inch, 4*inch])
            physical_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f9ff')),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            
            story.append(physical_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Risk Assessment Section
        if risk_assessment:
            story.append(Paragraph("Risk Assessment", self.styles['CustomHeading']))
            
            risk_level = risk_assessment.get('risk_level', 'Unknown')
            risk_score = risk_assessment.get('risk_score', 0)
            recommendation = risk_assessment.get('recommendation', 'Consult healthcare provider')
            risk_factors = risk_assessment.get('risk_factors', [])
            
            # Risk level box
            if risk_level == 'Very High':
                risk_color = colors.HexColor('#dc2626')
                risk_bg = colors.HexColor('#fee2e2')
            elif risk_level == 'High':
                risk_color = colors.HexColor('#ea580c')
                risk_bg = colors.HexColor('#ffedd5')
            elif risk_level == 'Moderate':
                risk_color = colors.HexColor('#0891b2')
                risk_bg = colors.HexColor('#cffafe')
            else:
                risk_color = colors.HexColor('#16a34a')
                risk_bg = colors.HexColor('#dcfce7')
            
            risk_box = Paragraph(
                f"<b>Risk Level:</b> {risk_level}<br/>"
                f"<b>Risk Score:</b> {risk_score} points<br/>"
                f"<b>Recommendation:</b> {recommendation}",
                ParagraphStyle(
                    'RiskBox',
                    parent=self.styles['Normal'],
                    fontSize=11,
                    borderColor=risk_color,
                    borderWidth=2,
                    borderPadding=12,
                    backColor=risk_bg,
                    spaceAfter=15
                )
            )
            story.append(risk_box)
            
            # Risk factors
            if risk_factors:
                story.append(Paragraph("<b>Identified Risk Factors:</b>", self.styles['CustomBody']))
                for factor in risk_factors:
                    story.append(Paragraph(f"• {factor}", 
                        ParagraphStyle('RiskFactor', parent=self.styles['Normal'], 
                                      fontSize=10, leftIndent=20, spaceAfter=6)))
                story.append(Spacer(1, 0.2*inch))
        
        # Recommendations Section
        story.append(Paragraph("Medical Recommendations", self.styles['CustomHeading']))
        
        if risk_level in ['Very High', 'High']:
            recommendations = [
                "🚨 <b>URGENT:</b> Schedule an appointment with your doctor immediately",
                "📋 Bring this report to your medical consultation",
                "🔬 Be prepared for additional diagnostic tests (mammogram, ultrasound, or biopsy)",
                "📝 Write down all your symptoms and when they started",
                "👥 Consider bringing a family member or friend to your appointment",
                "📞 Don't hesitate to seek emergency care if symptoms worsen"
            ]
        elif risk_level == 'Moderate':
            recommendations = [
                "📅 Schedule a medical consultation within the next 1-2 weeks",
                "📋 Bring this report to discuss with your healthcare provider",
                "🔍 Your doctor may recommend imaging tests for further evaluation",
                "📝 Keep track of any changes in your symptoms",
                "💪 Maintain a healthy lifestyle while awaiting your appointment"
            ]
        else:
            recommendations = [
                "✅ Continue regular breast self-examinations monthly",
                "📅 Follow your doctor's recommended screening schedule",
                "🏃 Maintain a healthy lifestyle with regular exercise",
                "🥗 Eat a balanced diet rich in fruits and vegetables",
                "📊 Be aware of any changes and report them to your doctor",
                "📚 Stay informed about breast health"
            ]
        
        for rec in recommendations:
            story.append(Paragraph(rec, 
                ParagraphStyle('Recommendation', parent=self.styles['Normal'], 
                              fontSize=10, spaceAfter=10, leading=14)))
        
        story.append(Spacer(1, 0.3*inch))
        
        # Important Notes
        story.append(Paragraph("Important Notes", self.styles['CustomHeading']))
        notes = [
            "<b>This is a screening tool only:</b> It cannot diagnose cancer. Only medical tests and "
            "professional evaluation can provide a definitive diagnosis.",
            
            "<b>Symptoms don't always mean cancer:</b> Many breast symptoms are caused by benign "
            "(non-cancerous) conditions. Professional evaluation is needed to determine the cause.",
            
            "<b>Early detection saves lives:</b> If you have concerning symptoms, don't delay seeking "
            "medical attention. Early detection significantly improves treatment outcomes.",
            
            "<b>Follow-up is essential:</b> Regardless of this screening result, continue regular "
            "check-ups and follow your doctor's recommendations."
        ]
        
        for note in notes:
            story.append(Paragraph(note, 
                ParagraphStyle('Note', parent=self.styles['Normal'], 
                              fontSize=9, spaceAfter=10, leading=12)))
        
        # Footer
        footer_text = Paragraph(
            f"<i>Symptom-Based Screening Report | Report ID: {prediction_data.get('report_id', 'N/A')} | "
            f"Generated by AI Breast Cancer Screening System | For Medical Consultation Only</i>",
            ParagraphStyle(
                'Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey,
                alignment=TA_CENTER
            )
        )
        story.append(Spacer(1, 0.5*inch))
        story.append(footer_text)
        
        # Build PDF
        doc.build(story)
        return output_path
