"""
PDF Report Generator for Breast Cancer Detection Results
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os

class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
    
    def setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#0369a1'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#0891b2'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12,
            alignment=TA_LEFT
        ))
    
    def generate_report(self, prediction_data, output_path='reports/prediction_report.pdf'):
        """Generate PDF report for prediction"""
        
        # Create reports directory
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Create PDF document
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        
        # Title
        title = Paragraph("Breast Cancer Detection Report", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.3*inch))
        
        # Report metadata
        report_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        metadata = Paragraph(f"<b>Report Generated:</b> {report_date}", self.styles['CustomBody'])
        story.append(metadata)
        story.append(Spacer(1, 0.2*inch))
        
        # Disclaimer
        disclaimer = Paragraph(
            "<b>MEDICAL DISCLAIMER:</b> This report is generated by an AI system for educational "
            "and research purposes only. It should NOT be used as a substitute for professional "
            "medical advice, diagnosis, or treatment. Always consult qualified healthcare professionals.",
            ParagraphStyle(
                'Disclaimer',
                parent=self.styles['Normal'],
                fontSize=9,
                textColor=colors.red,
                borderColor=colors.red,
                borderWidth=1,
                borderPadding=10,
                spaceAfter=20
            )
        )
        story.append(disclaimer)
        story.append(Spacer(1, 0.3*inch))
        
        # Prediction Results Section
        story.append(Paragraph("Prediction Results", self.styles['CustomHeading']))
        
        # Main prediction result
        prediction_label = prediction_data['best_model']['prediction_label']
        confidence = prediction_data['best_model']['confidence'] * 100
        
        result_color = colors.red if prediction_label == 'Malignant' else colors.green
        
        result_data = [
            ['Diagnosis', prediction_label],
            ['Confidence Level', f"{confidence:.2f}%"],
            ['Best Model', prediction_data['best_model']['name']],
            ['Risk Assessment', prediction_data.get('risk_assessment', {}).get('message', 'N/A')]
        ]
        
        result_table = Table(result_data, colWidths=[2*inch, 4*inch])
        result_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e0f2fe')),
            ('BACKGROUND', (1, 0), (1, 0), result_color),
            ('TEXTCOLOR', (1, 0), (1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('FONTSIZE', (1, 0), (1, 0), 14),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        
        story.append(result_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Model Comparison Section
        if 'all_models' in prediction_data and prediction_data['all_models'] and len(prediction_data['all_models']) > 1:
            story.append(Paragraph("Model Comparison", self.styles['CustomHeading']))
            
            model_data = [['Model Name', 'Prediction', 'Confidence']]
            for model_name, model_result in prediction_data['all_models'].items():
                model_data.append([
                    model_name,
                    model_result.get('prediction_label', 'N/A'),
                    f"{model_result.get('confidence', 0)*100:.2f}%"
                ])
            
            model_table = Table(model_data, colWidths=[2.5*inch, 2*inch, 1.5*inch])
            model_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0891b2')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ]))
            
            story.append(model_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Feature Importance Section
        if 'feature_importance' in prediction_data and prediction_data['feature_importance'] and len(prediction_data['feature_importance']) > 0:
            story.append(Paragraph("Top Contributing Features", self.styles['CustomHeading']))
            
            feature_data = [['Feature Name', 'Value', 'Importance']]
            for feature in prediction_data['feature_importance'][:10]:
                feature_data.append([
                    feature.get('name', 'N/A'),
                    f"{feature.get('value', 0):.4f}",
                    f"{feature.get('importance', 0):.4f}"
                ])
            
            feature_table = Table(feature_data, colWidths=[3*inch, 1.5*inch, 1.5*inch])
            feature_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0891b2')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            
            story.append(feature_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Recommendations Section
        story.append(Paragraph("Recommendations", self.styles['CustomHeading']))
        
        if prediction_label == 'Malignant':
            recommendations = [
                "• Immediate consultation with an oncologist is strongly recommended",
                "• Additional diagnostic tests (biopsy, imaging) should be performed",
                "• Discuss treatment options with healthcare team",
                "• Consider seeking a second opinion from a specialist",
                "• Maintain detailed medical records and test results"
            ]
        else:
            recommendations = [
                "• Continue regular screening and monitoring",
                "• Maintain healthy lifestyle and preventive measures",
                "• Schedule follow-up appointments as recommended",
                "• Report any changes or symptoms to healthcare provider",
                "• Stay informed about breast health"
            ]
        
        for rec in recommendations:
            story.append(Paragraph(rec, self.styles['CustomBody']))
        
        story.append(Spacer(1, 0.3*inch))
        
        # Footer
        footer_text = Paragraph(
            "<i>This report was generated by an AI-based Breast Cancer Detection System. "
            "Report ID: " + prediction_data.get('report_id', 'N/A') + "</i>",
            ParagraphStyle(
                'Footer',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.grey,
                alignment=TA_CENTER
            )
        )
        story.append(Spacer(1, 0.5*inch))
        story.append(footer_text)
        
        # Build PDF
        doc.build(story)
        
        return output_path
